### ISSUE TITLE
Work on Homebridge 2.0?

### ISSUE THREAD

**Issue by djrolling** [uswong/homebridge-cmd4-bondbridge#4]
With the production release of Homebridge 2.0 on May 4, I'm checking all my important plug-ins for 2.0 compatibility.

Hoping someone already tested this as I typically struggle installing/configuring plug-ins let alone testing properly.

**Comment by uswong** [comment]
Yes, it works as per normal on Homebridge 2.0. 

If you come across some warnings like the following:

[UPDATE CHECK FAILED] Could not check for newer versions of homebridge-bondbridge due to error TypeError: latestVersion is not a function

Ignore it, I will correct it in my next update.  It has nothing to do with the running of the plugin.

**Comment by djrolling** [comment]
THANK YOU! for the rapid response.
